---
title: "scratch_ML"
author: "Robert Duc Bui"
date: "4/28/2021"
output: html_document
---

```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
library(dbplyr)
library(RMySQL)
library(RSQLite)
library(DALEX)
library(DALEXtra)
library(patchwork)
library(yaml)

con_air <- dbConnect(RMySQL::MySQL(),
                     dbname = "airlines",
                     host = "mdsr.cdc7tgkkqd0n.us-east-1.rds.amazonaws.com",
                     user = "mdsr_public",
                     password = "ImhsmflMDSwR")

dbListTables(con_air)
```

```{r}
cols <- c("AA"="#0078d2",
          "AS"="#9abd63",
          "B6"="#7eb4f7",
          "DL"="#ab1740",
          "F9"="#006341",
          "HA"="#cb0686",
          "NK"="#f7e501",
          "OO"="#6d8ba6",
          "UA"="#00319b",
          "VX"="#dc2424",
          "WN"="#f29802",
          "YV"="#251f21")

airline_names <- c(
  "AA" = "American (incl. Subsidiaries)",
  "AS" = "Alaska",
  "B6" = "JetBlue",
  "DL" = "Delta (incl. Subsidiaries)",
  "F9" = "Frontier",
  "HA" = "Hawaii",
  "NK" = "Spirit",
  "OO" = "SkyWest",
  "UA" = "United (incl. Subsidiaries)",
  "VX" = "Virgin",
  "WN" = "Southwest",
  "YV" = "Mesa"
) %>% 
  as.data.frame() %>% 
  rownames_to_column("parent_carrier")

colnames(airline_names)[2] <- "name"

colors <- as.data.frame(cols) %>% 
  rownames_to_column()

colnames(colors)[1] <- "parent_carrier"
colnames(colors)[2] <- "color"

parent_carrier <- c("DL","AA","AS","B6","UA","DL","UA","F9","WN","HA","AA","NK","AA","OO","UA","AA","VX","WN","UA","YV")

local = "MSP"
```

```{r}
alldata_local <- tbl(con_air,"flights") %>% 
  filter(origin == local,
         cancelled == 0,
         diverted == 0) %>% 
  select(time=sched_dep_time,carrier,dest,distance,date=time_hour,dep_delay) %>% 
  collect()

carriers <- tbl(con_air,"flights") %>% 
  group_by(carrier) %>% 
  summarise() %>% 
  collect() %>% 
  cbind(parent_carrier) %>% 
  left_join(colors)
```

```{r}
alldata_local %>% 
  pryr::object_size()

alldata_local <- alldata_local %>% 
  left_join(carriers) %>% 
  mutate(date = lubridate::date(date),
         carrier = parent_carrier) %>% 
  select(-c(parent_carrier,color))
```

```{r}
set.seed(8675309)

splitkey <- initial_split(alldata_local, prop = .75)

flight_training <- splitkey %>% training()
flight_testing  <- splitkey %>% testing()

ranger_recipe <- 
  recipe(dep_delay ~ .,
         data = flight_training) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  #step_dummy(all_nominal(),-all_outcomes()) %>% 
  #step_zv(all_predictors()) 
  step_scale(`distance`)

ranger_spec <- 
  rand_forest(mtry = 6,
              min_n = 10,
              trees = 200) %>% 
  set_mode("regression") %>% 
  set_engine("ranger")

ranger_wf <-
  workflow() %>% 
  add_recipe(ranger_recipe) %>% 
  add_model(ranger_spec)

set.seed(8675309)
ranger_fit <- ranger_wf %>% 
  fit(flight_training)

lasso_recipe <-
  recipe(dep_delay ~ .,
         data = flight_training) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  step_center(all_numeric(),-all_outcomes()) %>% 
  step_scale(all_numeric(),-all_outcomes()) %>% 
  step_dummy(all_nominal(),-all_outcomes()) %>% 
  step_zv(all_predictors())
  
lasso_spec <-
  linear_reg(mixture = 1) %>% 
  set_engine("glmnet") %>% 
  set_args(penalty = tune()) %>% 
  set_mode("regression")

lasso_wf <-
  workflow() %>% 
  add_recipe(lasso_recipe) %>% 
  add_model(lasso_spec)

set.seed(8675309)
lasso_cv <- 
  vfold_cv(flight_training, v = 5)

penalty_grid <- 
  grid_regular(penalty(),
               levels = 10)

lasso_tune <- 
  lasso_wf %>% 
  tune_grid(
    resamples = lasso_cv,
    grid = penalty_grid
  )

best_param <- 
  lasso_tune %>% 
  select_best(metric = "rmse")

lasso_final_wf <-
  lasso_wf %>% 
  finalize_workflow(best_param)

lasso_fit <- 
  lasso_final_wf %>% 
  fit(flight_training)

flight_testing %>% 
  select(dep_delay) %>% 
  bind_cols(predict(ranger_fit, new_data = flight_testing)) %>% 
  summarize(testing_ranger_rmse = sqrt(mean((dep_delay - .pred) ^ 2)))

flight_testing %>% 
  select(dep_delay) %>% 
  bind_cols(predict(lasso_fit, new_data = flight_testing)) %>% 
  summarize(testing_lasso_rmse = sqrt(mean((dep_delay - .pred) ^ 2)))
```

```{r}
alldata_local_nooutliers <- alldata_local %>% 
  mutate(z = round((dep_delay - mean(dep_delay))/sd(dep_delay))) %>% 
  arrange(desc(z)) %>% 
  ungroup() %>% 
  filter(abs(z)<=3) %>% 
  select(-z)
```

```{r}
set.seed(8675309)

splitkey <- initial_split(alldata_local_nooutliers, prop = .75)

flight_training1 <- splitkey %>% training()
flight_testing1  <- splitkey %>% testing()

ranger_recipe1 <- 
  recipe(dep_delay ~ .,
         data = flight_training1) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  #step_dummy(all_nominal(),-all_outcomes()) %>% 
  #step_zv(all_predictors()) 
  step_scale(`distance`)

ranger_spec1 <- 
  rand_forest(mtry = 6,
              min_n = 10,
              trees = 200) %>% 
  set_mode("regression") %>% 
  set_engine("ranger")

ranger_wf1 <-
  workflow() %>% 
  add_recipe(ranger_recipe1) %>% 
  add_model(ranger_spec1)

set.seed(8675309)
ranger_fit1 <- ranger_wf1 %>% 
  fit(flight_training1)

lasso_recipe1 <-
  recipe(dep_delay ~ .,
         data = flight_training1) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  step_center(all_numeric(),-all_outcomes()) %>% 
  step_scale(all_numeric(),-all_outcomes()) %>% 
  step_dummy(all_nominal(),-all_outcomes()) %>% 
  step_zv(all_predictors())
  
lasso_spec1 <-
  linear_reg(mixture = 1) %>% 
  set_engine("glmnet") %>% 
  set_args(penalty = tune()) %>% 
  set_mode("regression")

lasso_wf1 <-
  workflow() %>% 
  add_recipe(lasso_recipe1) %>% 
  add_model(lasso_spec1)

set.seed(8675309)
lasso_cv1 <- 
  vfold_cv(flight_training1, v = 5)

penalty_grid <- 
  grid_regular(penalty(),
               levels = 10)

lasso_tune1 <- 
  lasso_wf1 %>% 
  tune_grid(
    resamples = lasso_cv1,
    grid = penalty_grid
  )

best_param1 <- 
  lasso_tune1 %>% 
  select_best(metric = "rmse")

lasso_final_wf1 <-
  lasso_wf1 %>% 
  finalize_workflow(best_param1)

lasso_fit1 <- 
  lasso_final_wf1 %>% 
  fit(flight_training1)
```

```{r}
mlp_recipe1 <-
  recipe(dep_delay ~ .,
         data = flight_training1) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  step_center(all_numeric(),-all_outcomes()) %>% 
  step_scale(all_numeric(),-all_outcomes()) 
  #step_dummy(all_nominal(),-all_outcomes()) %>% 
  #step_zv(all_predictors())

mlp_spec1 <- 
  mlp(epochs = 100, 
      hidden_units = 5, 
      dropout = .1) %>% 
  set_mode("regression") %>% 
  set_engine("keras", verbose = 0)

mlp_wf1 <-
  workflow() %>% 
  add_recipe(mlp_recipe1) %>% 
  add_model(mlp_spec1)

set.seed(8675309)
mlp_fit1 <- mlp_wf1 %>% 
  fit(flight_training1)
```

```{r}
ranger_fit1
lasso_fit1

ranger_parsed <- save(ranger_fit1,file = "trained_workflows/ranger_fit1.RData")
lasso_parsed <- save(lasso_fit1,file = "trained_workflows/lasso_fit1.RData")
```

```{r}
flight_training1 %>% 
  select(dep_delay) %>% 
  bind_cols(predict(ranger_fit1, new_data = flight_training1)) %>% 
  summarise(testing_ranger_rmse1 = sqrt(mean((dep_delay - .pred) ^ 2)))

flight_training1 %>% 
  select(dep_delay) %>% 
  bind_cols(predict(lasso_fit1, new_data = flight_training1)) %>% 
  summarise(testing_lasso_rmse1 = sqrt(mean((dep_delay - .pred) ^ 2)))
```

```{r}
load("trained_workflows/ranger_fit1.RData")
load("trained_workflows/lasso_fit1.RData")
load("trained_workflows/mlp_fit1.RData")
```

```{r}
lasso_explain <- 
  explain_tidymodels(
    model = lasso_fit1,
    data = flight_training1 %>% select(-dep_delay), 
    y = flight_training1 %>% pull(dep_delay),
    label = "lasso"
  )

rf_explain <- 
  explain_tidymodels(
    model = ranger_fit1,
    data = flight_training1 %>% select(-dep_delay), 
    y = flight_training1 %>% pull(dep_delay),
    label = "rf"
  )

mlp_explain <- 
  explain_tidymodels(
    model = mlp_fit1,
    data = flight_training1 %>% select(-dep_delay), 
    y = flight_training1 %>% pull(dep_delay),
    label = "mlp"
  )

lasso_mod_perf <- model_performance(lasso_explain)
rf_mod_perf <-  model_performance(rf_explain)
mlp_mod_perf <-  model_performance(mlp_explain)

hist_plot <- 
  plot(lasso_mod_perf,
       rf_mod_perf,
       #mlp_mod_perf,
       geom = "histogram")
box_plot <-
  plot(lasso_mod_perf,
       rf_mod_perf, 
       #mlp_mod_perf,
       geom = "boxplot")

hist_plot + box_plot

set.seed(8675309)
lasso_var_imp <- 
  model_parts(
    lasso_explain
    )
set.seed(8675309)
rf_var_imp <- 
  model_parts(
    rf_explain
    )

set.seed(8675309)
mlp_var_imp <- 
  model_parts(
    mlp_explain
    )

plot(lasso_var_imp, show_boxplots = TRUE)  / plot(rf_var_imp, show_boxplots = TRUE) #/ plot(mlp_var_imp, show_boxplots = TRUE)

```

