---
title: "scratch"
author: "Robert Duc Bui"
date: "4/19/2021"
output: html_document
---

```{r}
library(tidyverse)
library(dbplyr)
library(mdsr)
library(RMySQL)
library(RSQLite)
library(lubridate)
library(ggforce)
library(networkD3)
library(plotly)

con_air <- dbConnect(RMySQL::MySQL(),
                     dbname = "airlines",
                     host = "mdsr.cdc7tgkkqd0n.us-east-1.rds.amazonaws.com",
                     user = "mdsr_public",
                     password = "ImhsmflMDSwR")

dbListTables(con_air)
```

```{r}
cols <- c("AA"="#0078d2",
          "AS"="#9abd63",
          "B6"="#7eb4f7",
          "DL"="#ab1740",
          "F9"="#006341",
          "HA"="#cb0686",
          "NK"="#f7e501",
          "OO"="#6d8ba6",
          "UA"="#00319b",
          "VX"="#dc2424",
          "WN"="#f29802",
          "YV"="#251f21")

airline_names <- c(
  "AA" = "American (incl. Subsidiaries)",
  "AS" = "Alaska",
  "B6" = "JetBlue",
  "DL" = "Delta (incl. Subsidiaries)",
  "F9" = "Frontier",
  "HA" = "Hawaii",
  "NK" = "Spirit",
  "OO" = "SkyWest",
  "UA" = "United (incl. Subsidiaries)",
  "VX" = "Virgin",
  "WN" = "Southwest",
  "YV" = "Mesa"
) %>% 
  as.data.frame() %>% 
  rownames_to_column("parent_carrier")

colnames(airline_names)[2] <- "name"

colors <- as.data.frame(cols) %>% 
  rownames_to_column()

colnames(colors)[1] <- "parent_carrier"
colnames(colors)[2] <- "color"

parent_carrier <- c("DL","AA","AS","B6","UA","DL","UA","F9","WN","HA","AA","NK","AA","OO","UA","AA","VX","WN","UA","YV")
```

```{r}
local = "MSP"

flights_fromlocal <- tbl(con_air,"flights") %>% 
  filter(origin == local) %>% 
  mutate(date = substr(time_hour,1,10)) %>%
  select(date,year,month,day,hour,carrier,dest,dep_delay,distance) %>% 
  ungroup() %>% 
  collect()

carriers <- tbl(con_air,"flights") %>% 
  group_by(carrier) %>% 
  summarise() %>% 
  collect() %>% 
  cbind(parent_carrier) %>% 
  left_join(colors)

routes_fromlocal <- tbl(con_air,"flights") %>% 
  filter(origin == local) %>% 
  group_by(dest) %>% 
  summarise(n=n()) %>% 
  collect()

routes_fromlocal <- tbl(con_air,"airports") %>% 
  select(dest=faa,lat,lon,city) %>% 
  collect() %>% 
  right_join(routes_fromlocal) %>% 
  na.omit()

local_geo <- tbl(con_air,"airports") %>% 
  filter(faa == local) %>% 
  select(lat,lon) %>% 
  collect()

airports_no_flights <- tbl(con_air,"airports") %>% 
  select(dest=faa,lat,lon,city) %>% 
  collect() %>% 
  anti_join(routes_fromlocal) %>% 
  na.omit()
```


```{r}
flights_fromlocal %>% 
  #head(15000) %>% 
  left_join(carriers) %>% 
  group_by(parent_carrier) %>% 
  summarise(delay = mean(dep_delay),
            n = n()) %>% 
  left_join(airline_names) %>% 
  ggplot(
    aes(
      x = fct_reorder(name,delay),
      y = delay,
      fill = parent_carrier,
      color = parent_carrier,
      text = paste("Carrier: ", name,"\n",
                   "Number of flights: ", n, "\n",
                   "Average Delay: ~",round(delay)," minutes","\n", sep = "")
    )
  )+
  geom_col()+
  coord_flip()+
  scale_fill_manual(values = cols)+
  scale_color_manual(values = cols)+
  theme_minimal()+
  labs(
    x = "",
    y = paste("Average Delay (Minutes) at",local)
  )+
  theme(legend.position = "none") -> p0

p0 %>% ggplotly(tooltip = c("text"))
```

```{r}
flights_fromlocal %>% 
  #head(15000) %>% 
  left_join(carriers) %>% 
  group_by(year) %>% 
  summarise(delay = mean(dep_delay),
            n = n()) %>% 
  #left_join(airline_names) %>% 
  ggplot(
    aes(
      x = year,
      y = delay,
      #fill = parent_carrier,
      #color = parent_carrier,
      group = 1,
      text = paste("Year: ", year, "\n",
                   "Number of flights: ", n, "\n",
                   "Average Delay: ~",round(delay)," minutes","\n", sep = "")
    )
  )+
  geom_line(size = 0.7)+
  geom_point()+
  #scale_fill_manual(values = cols)+
  #scale_color_manual(values = cols)+
  #facet_wrap(~name)+
  theme_minimal()+
  labs(
    x = "Year",
    y = "Average Delay (Minutes)"
  )+
  theme(legend.position = "none") -> p1a

p1a %>% ggplotly(tooltip = c("text"))
```

```{r}
flights_fromlocal %>% 
  #head(15000) %>% 
  left_join(carriers) %>% 
  group_by(year,parent_carrier) %>% 
  summarise(delay = mean(dep_delay),
            n = n()) %>% 
  left_join(airline_names) %>% 
  ggplot(
    aes(
      x = year,
      y = delay,
      fill = parent_carrier,
      color = parent_carrier,
      group = 1,
      text = paste("Carrier: ", name,"\n",
                   "Year: ", year, "\n",
                   "Number of flights: ", n, "\n",
                   "Average Delay: ~",round(delay)," minutes","\n", sep = "")
    )
  )+
  geom_line(size = 0.7)+
  geom_point()+
  scale_fill_manual(values = cols)+
  scale_color_manual(values = cols)+
  facet_wrap(~name)+
  theme_minimal()+
  labs(
    x = "Year",
    y = "Average Delay (Minutes)"
  )+
  theme(legend.position = "none") -> p1

p1 %>% ggplotly(tooltip = c("text"))
```

```{r}
flights_fromlocal %>% 
  #head(15000) %>% 
  left_join(carriers) %>% 
  group_by(month) %>% 
  summarise(delay = mean(dep_delay),
            n = n()) %>% 
  #left_join(airline_names) %>% 
  ggplot(
    aes(
      x = month,
      y = delay,
      #fill = parent_carrier,
      #color = parent_carrier,
      group = 1,
      text = paste("Month: ", month, "\n",
                   "Number of flights: ", n, "\n",
                   "Average Delay: ~",round(delay)," minutes","\n", sep = "")
    )
  )+
  geom_line(size = 0.7)+
  geom_point()+
  #scale_fill_manual(values = cols)+
  #scale_color_manual(values = cols)+
  #facet_wrap(~name)+
  theme_minimal()+
  labs(
    x = "Year",
    y = "Average Delay (Minutes)"
  )+
  theme(legend.position = "none") -> p2a

p2a %>% ggplotly(tooltip = c("text"))
```

```{r}
flights_fromlocal %>% 
  left_join(carriers) %>% 
  group_by(month,parent_carrier) %>% 
  summarise(delay = mean(dep_delay),
            n=n()) %>% 
  left_join(airline_names) %>% 
  ggplot(
    aes(
      x = month,
      y = delay,
      fill = parent_carrier,
      color = parent_carrier,
      group = 1,
      text = paste("Carrier: ", name,"\n",
                   "Month: ", month, "\n",
                   "Number of flights: ", n, "\n",
                   "Average Delay: ~",round(delay)," minutes","\n", sep = "")
    )
  )+
  geom_line(size = 0.7)+
  geom_point()+
  scale_fill_manual(values = cols)+
  scale_color_manual(values = cols)+
  facet_wrap(~name)+
  theme_minimal()+
  labs(
    x = "Month",
    y = "Average Delay (Minutes)"
  )+
  theme(legend.position = "none") -> p2

p2 %>% ggplotly(tooltip = c("text"))
```

```{r}
flights_fromlocal %>% 
  mutate(time_day = date(date),
         wday = wday(time_day)) %>% 
  left_join(carriers) %>%
  group_by(wday,parent_carrier) %>% 
  summarise(delay = mean(dep_delay),
            n=n()) %>% 
  left_join(airline_names) %>% 
  ggplot(
    aes(
      x = wday,
      y = delay,
      fill = parent_carrier,
      color = parent_carrier,
      group = 1,
      text = paste("Carrier: ", name,"\n",
                   "Day of the Week: ", wday, "\n",
                   "Number of flights: ", n, "\n",
                   "Average Delay: ~",round(delay)," minutes","\n", sep = "")
    )
  )+
  geom_line(size = 0.7)+
  geom_point()+
  scale_fill_manual(values = cols)+
  scale_color_manual(values = cols)+
  facet_wrap(~name)+
  theme_minimal()+
  labs(
    x = "Day of the Week (1 is Sunday)",
    y = "Average Delay (Minutes)"
  )+
  theme(legend.position = "none") -> p3

p3 %>% ggplotly(tooltip = c("text"))
```

```{r}
flights_fromlocal %>% 
  left_join(carriers) %>%
  group_by(hour,parent_carrier) %>% 
  summarise(delay = mean(dep_delay),
            n = n()) %>% 
  left_join(airline_names) %>% 
  ggplot(
    aes(
      x = hour,
      y = delay,
      fill = parent_carrier,
      color = parent_carrier,
      group = 1,
      text = paste("Carrier: ", name,"\n",
                   "Hour of the Day: ", hour, "\n",
                   "Number of flights: ", n, "\n",
                   "Average Delay: ~",round(delay)," minutes","\n", sep = "")
    )
  )+
  geom_line(size = 0.7)+
  geom_point()+
  scale_fill_manual(values = cols)+
  scale_color_manual(values = cols)+
  facet_wrap(~name)+
  theme_minimal()+
  labs(
    x = "Hour (Rounded Down)",
    y = "Average Delay (Minutes)"
  )+
  theme(legend.position = "none") -> p4

p4 %>% ggplotly(tooltip = c("text"))
```

```{r}
flights_fromlocal %>% 
  group_by(dest) %>% 
  summarise(delay = mean(dep_delay)) %>% 
  left_join(routes_fromlocal) -> d2

geo <- list(
      #scope = "usa",
      projection = list(
      type = 'orthographic',
      rotation = list(lon = local_geo$lon, lat = local_geo$lat, roll = 0)
      ),
      showland = T,
      landcolor = 'transparent',
      countrycolor = 'transparent'
    )
    
p <- plot_geo() %>% 
      add_markers(
        data = airports_no_flights, x = ~lon, y = ~lat, 
        size = .1, 
        opacity=.16,
        hoverinfo = "none",
        symbol = I("x-thin"),
      ) %>%
      add_segments(
        data = d2, 
        x = local_geo$lon, xend = ~lon,
        y = local_geo$lat, yend = ~lat,
        alpha=.175,size = ~sqrt(n),
        opacity = .5
      ) %>% 
      add_markers(
        data = d2, x = ~lon, y = ~lat, 
        text = ~paste("Destination Airport:   ", dest, "\n","City:                          ",city,"\n","Average Delay:         ",round(delay)," minutes","\n","Annual # Flights:      ",n/8,sep=""), 
        hoverinfo = "text",
        size = ~delay^2
      ) %>% 
      add_markers(
        data = d2, x = local_geo$lon, y = local_geo$lat, 
        text = paste(local), 
        hoverinfo = "text",
        size = I(10),
        symbol = I("star"),
        color = I("red")
      )

airports_no_flights

ggplotly(p) %>% 
      layout(
        title = 'Delay by Destination Airport',
        geo = geo, showlegend = F,
        plot_bgcolor='transparent',
        paper_bgcolor='transparent'
      )
```
