---
title: "scratch_stack"
author: "Robert Duc Bui"
date: "4/30/2021"
output: html_document
---

```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
library(dbplyr)
library(RMySQL)
library(RSQLite)
library(stacks)
library(DALEX)
library(DALEXtra)
library(patchwork)
library(yaml)

con_air <- dbConnect(RMySQL::MySQL(),
                     dbname = "airlines",
                     host = "mdsr.cdc7tgkkqd0n.us-east-1.rds.amazonaws.com",
                     user = "mdsr_public",
                     password = "ImhsmflMDSwR")

dbListTables(con_air)
```

```{r}
cols <- c("AA"="#0078d2",
          "AS"="#9abd63",
          "B6"="#7eb4f7",
          "DL"="#ab1740",
          "F9"="#006341",
          "HA"="#cb0686",
          "NK"="#f7e501",
          "OO"="#6d8ba6",
          "UA"="#00319b",
          "VX"="#dc2424",
          "WN"="#f29802",
          "YV"="#251f21")

airline_names <- c(
  "AA" = "American (incl. Subsidiaries)",
  "AS" = "Alaska",
  "B6" = "JetBlue",
  "DL" = "Delta (incl. Subsidiaries)",
  "F9" = "Frontier",
  "HA" = "Hawaii",
  "NK" = "Spirit",
  "OO" = "SkyWest",
  "UA" = "United (incl. Subsidiaries)",
  "VX" = "Virgin",
  "WN" = "Southwest",
  "YV" = "Mesa"
) %>% 
  as.data.frame() %>% 
  rownames_to_column("parent_carrier")

colnames(airline_names)[2] <- "name"

colors <- as.data.frame(cols) %>% 
  rownames_to_column()

colnames(colors)[1] <- "parent_carrier"
colnames(colors)[2] <- "color"

parent_carrier <- c("DL","AA","AS","B6","UA","DL","UA","F9","WN","HA","AA","NK","AA","OO","UA","AA","VX","WN","UA","YV")

local = "MSP"

ctrl_grid <- control_stack_grid()
ctrl_res <- control_stack_resamples()

```

```{r}
alldata_local <- tbl(con_air,"flights") %>% 
  filter(origin == local,
         cancelled == 0,
         diverted == 0) %>% 
  select(time=sched_dep_time,carrier,dest,distance,date=time_hour,dep_delay) %>% 
  collect()

carriers <- tbl(con_air,"flights") %>% 
  group_by(carrier) %>% 
  summarise() %>% 
  collect() %>% 
  cbind(parent_carrier) %>% 
  left_join(colors)
```

```{r}
alldata_local %>% 
  pryr::object_size()

logdata_local <- alldata_local %>% 
  left_join(carriers) %>% 
  mutate(date = lubridate::date(date),
         carrier = parent_carrier) %>% 
  select(-c(parent_carrier,color)) %>% 
  mutate(log_delay = case_when(dep_delay <= 1 ~ log(1),
                                   dep_delay > 1 ~ dep_delay %>% log())) %>% 
  filter(is.double(log_delay) == T) %>% 
  select(-dep_delay)
  
logdata_local %>% pryr::object_size()
```

```{r}
logdata_local %>% 
  mutate(naive_avg = mean(log_delay)) %>% 
  summarise(naive_log_rmse = sqrt(mean((log_delay - naive_avg) ^ 2)))
```
  
```{r}
set.seed(8675309)

splitkey <- initial_split(logdata_local, prop = .75)

flight_training_log <- splitkey %>% training()
flight_testing_log  <- splitkey %>% testing()
```

```{r}
ranger_recipe_log <- 
  recipe(log_delay ~ .,
         data = flight_training_log) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  #step_dummy(all_nominal(),-all_outcomes()) %>% 
  #step_zv(all_predictors()) 
  step_scale(`distance`)

ranger_spec_log <- 
  rand_forest(mtry = 6,
              min_n = 10,
              trees = 200) %>% 
  set_mode("regression") %>% 
  set_engine("ranger")

ranger_wf_log <-
  workflow() %>% 
  add_recipe(ranger_recipe_log) %>% 
  add_model(ranger_spec_log)


set.seed(8675309)
ranger_fit_log <- ranger_wf_log %>% 
  fit(flight_training_log)

flight_training_log %>% 
  select(log_delay) %>% 
  bind_cols(predict(ranger_fit_log, new_data = flight_training_log)) %>% 
  summarise(training_ranger_log_rmse = sqrt(mean((log_delay - .pred) ^ 2)))

```

```{r}
lasso_recipe_log <-
  recipe(log_delay ~ .,
         data = flight_training_log) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  step_dummy(all_nominal(),-all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_scale(`distance`)
  
lasso_spec_log <-
  linear_reg(mixture = 1) %>% 
  set_engine("glmnet") %>% 
  set_args(penalty = tune()) %>% 
  set_mode("regression")

lasso_wf_log <-
  workflow() %>% 
  add_recipe(lasso_recipe_log) %>% 
  add_model(lasso_spec_log)

set.seed(8675309)
lasso_cv_log <- 
  vfold_cv(flight_training_log, v = 5)

penalty_grid <- 
  grid_regular(penalty(),
               levels = 10)

lasso_tune_log <- 
  lasso_wf_log %>% 
  tune_grid(
    resamples = lasso_cv_log,
    grid = penalty_grid
  )

lasso_stackgrid <- 
  lasso_wf_log %>% 
  tune_grid(
    resamples = flights_cv,
    grid = penalty_grid,
    metrics = metric_set(rmse),
    control = ctrl_grid
  )

lasso_best_param_log <- 
  lasso_tune_log %>% 
  select_best(metric = "rmse")

lasso_final_wf_log <-
  lasso_wf_log %>% 
  finalize_workflow(lasso_best_param_log)

lasso_fit_log <- 
  lasso_final_wf_log %>% 
  fit(flight_training_log)

flight_training_log %>% 
  select(log_delay) %>% 
  bind_cols(predict(lasso_fit_log, new_data = flight_training_log)) %>% 
  summarise(training_lasso_log_rmse = sqrt(mean((log_delay - .pred) ^ 2)))

```

```{r}
mlp_recipe_log <-
  recipe(log_delay ~ .,
         data = flight_training_log) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_center(all_numeric(),-all_outcomes()) %>% 
  step_scale(all_numeric(),-all_outcomes()) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  step_dummy(all_nominal(),-all_outcomes()) %>% 
  step_zv(all_predictors())

mlp_spec_log <- 
  mlp(epochs = 100, 
      hidden_units = 10, 
      dropout = .05) %>% 
  set_mode("regression") %>% 
  set_engine("keras", verbose = 0)

mlp_wf_log <-
  workflow() %>% 
  add_recipe(mlp_recipe_log) %>% 
  add_model(mlp_spec_log)

set.seed(8675309)
mlp_fit_log <- 
  mlp_wf_log %>% 
  fit(flight_training_log)

flight_training_log %>% 
  select(log_delay) %>% 
  bind_cols(predict(mlp_fit_log, new_data = flight_training_log)) %>% 
  summarise(training_mlp_log_rmse = sqrt(mean((log_delay - .pred) ^ 2)))
```

```{r}
ranger_fit_log
lasso_fit_log
mlp_fit_log


save(ranger_fit_log,file = "trained_workflows/MSP/ranger_fit_log.RData")
save(lasso_fit_log,file = "trained_workflows/MSP/lasso_fit_log.RData")
save(mlp_fit_log,file = "trained_workflows/MSP/mlp_fit_log.RData")

```

```{r}
ctrl_grid <- control_stack_grid()
ctrl_res <- control_stack_resamples()

set.seed(8675309)
flights_cv <- vfold_cv(flight_training_log, v = 5)

ranger_recipe_log <- 
  recipe(log_delay ~ .,
         data = flight_training_log) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  #step_dummy(all_nominal(),-all_outcomes()) %>% 
  #step_zv(all_predictors()) 
  step_scale(`distance`)

ranger_spec_log <- 
  rand_forest(mtry = 6,
              min_n = 10,
              trees = 200) %>% 
  set_mode("regression") %>% 
  set_engine("ranger")

ranger_wf_log <-
  workflow() %>% 
  add_recipe(ranger_recipe_log) %>% 
  add_model(ranger_spec_log)

penalty_grid <- 
  grid_regular(penalty(),
               levels = 5)

lasso_recipe_log <-
  recipe(log_delay ~ .,
         data = flight_training_log) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  step_dummy(all_nominal(),-all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_scale(`distance`)
  
lasso_spec_log <-
  linear_reg(mixture = 1) %>% 
  set_engine("glmnet") %>% 
  set_args(penalty = tune()) %>% 
  set_mode("regression")

lasso_wf_log <-
  workflow() %>% 
  add_recipe(lasso_recipe_log) %>% 
  add_model(lasso_spec_log)
```


```{r}
ranger_logstack <-
  ranger_wf_log %>% 
  fit_resamples(flights_cv, 
                metrics = metric_set(rmse),
                control = ctrl_res)

save(ranger_logstack,file = "trained_workflows/MSP/ranger_logstack.RData")
```


```{r}
lasso_logstack <- 
  lasso_wf_log %>% 
  tune_grid(
    resamples = flights_cv,
    grid = penalty_grid,
    metrics = metric_set(rmse),
    control = ctrl_grid
  )

save(lasso_logstack,file = "trained_workflows/MSP/lasso_logstack.RData")
```

```{r}
knn_recipe_log <-
  recipe(log_delay ~ .,
         data = flight_training_log) %>% 
  step_corr(all_predictors(),-c(carrier,dest,date)) %>% 
  step_date(date, features = c("dow","month")) %>%
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  step_dummy(all_nominal(),-all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_scale(`distance`)

knn_mod <-
  nearest_neighbor(
    neighbors = tune("k")
  ) %>%
  set_engine("kknn") %>% 
  set_mode("regression")

# create the workflow
knn_wf <- 
  workflow() %>% 
  add_model(knn_mod) %>%
  add_recipe(knn_recipe_log)

knn_tune <- 
  knn_wf %>% 
  tune_grid(
    flights_cv,
    metrics = metric_set(rmse),
    grid = 4,
    control = ctrl_grid
  )
```


```{r}
flights_logstack <-
  stacks() %>% 
  add_candidates(ranger_logstack) %>% 
  add_candidates(lasso_logstack) 
  
```


```{r}
flights_blend <- flights_logstack %>% 
  blend_predictions()
```

